### ISSUE TITLE
Ability to view list of added repos and update it

### ISSUE THREAD

**Issue by dumityty** [lincolnh0/zendit#10]
When adding a new repo once you click Save there is no way of viewing the list of repos added (other than on the main zendit screen) and remove them or update them (ie. if you made a mistake and copied wrong repo link etc.)

I assume the list is saved in some config file locally in the user's home folder or in the zendit installation folder so could technically edit there if urgent.

**Comment by lincolnh0** [comment]
To be added in v1.2.0 release
