### ISSUE TITLE
Default PR template and Jira comment

### ISSUE THREAD

**Issue by dumityty** [lincolnh0/zendit#9]
When you open the Preferences would be nice to have a default template for both PR and Jira comment to standardise them and not have to write them manually.

Alternatively if not possible give templates in the README file that someone can copy paste into the Preferences.

**Comment by lincolnh0** [comment]
Added default templates to https://github.com/lincolnh0/zendit/blob/master/TEMPLATE.md for first time users to copy. 👍🏻
